### ISSUE TITLE
black: syntax error: Expected ')'

### ISSUE THREAD

**Issue by germanbraun** [black-sat/black#30] opened 2020-10-08 19:31 UTC
I got this syntax error but input seems to be well without unbalanced parenthesis 

black: syntax error: random.pltl: Expected ')'

I attached the formulae.
[random_parenthesis.pltl.txt](https://github.com/black-sat/black/files/5350937/random_parenthesis.pltl.txt)

**Comment by GabVenturato** [comment] 2020-10-08 22:37
I've noticed this problem too, but not yet reported (nor had time to fix it).

The problem is due to underscores in propositional names. If you write propositional names without underscores it should work.

**Comment by nicola-gigante** [comment] 2020-10-09 07:31
Thanks to both! The problem seems to be ours, we should allow underscore as part of identifiers. That is easily fixable in the lexer. I'll look into it as soon as possible.

**Comment by nicola-gigante** [comment] 2020-10-09 16:42
Fixed by PR #35

**Closed by nicola-gigante** 2020-10-09 16:43 UTC
Labels: bug
